#!/bin/sh

case "$1" in
	start)
		echo "Start aesdsocket daemon"
		start-stop-daemon -S -n /usr/bin/aesdsocket -a /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo "Stop aesdsocket daemon"
		start-stop-daemon -K -n aesdsocket
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
